### ISSUE TITLE
Server File Structure

### ISSUE THREAD

**Issue by Asmaathabet** [GSG-G7/Parent-assistent#26]
#### Backend Setup steps:
- [x]  add the main file structure 
- [x]  install needed modules 
- [x] make configurations for EsLint module 
- [x]   add the main configuration for app.js file 
- [x]   initial server to listen in port 5000 

#### File structure
* server/  
    * database/
       * config/
       * queries/
    * router/
    * controllers/
        * routes/
        * utils/
        * middlewares/
        * index.js
    * test/
        * queries/
        * routes/
        * index.js
   * app.js
   * index.js 
   * .gitignore
   * build/ react generated build file
#### Modules
* Dependencies:
   * express
   * cookie-parser
   * pg
   * jsonwebtoken
   * bcrypt
   * yup

* devDependencies :
   * tape
   * tap-spec
   * supertest
   * nodemon
   * eslint

> make configuration for eslint by :
./node_modules/.bin/eslint --init

**Comment by AlaaTaima** [comment]
Asma, I have already explained this issue in details, at issue #14 you can see it.
